fixtures:
  repositories:
    alternatives:     'git://github.com/adrienthebo/puppet-alternatives'
    apache:           'git://github.com/puppetlabs/puppetlabs-apache'
    apt:
      repo:           'git://github.com/puppetlabs/puppetlabs-apt'
      branch:         '1.8.x'
    concat:
      repo:           'git://github.com/puppetlabs/puppetlabs-concat'
      branch:         '1.2.x'
    file_concat:      'git://github.com/electrical/puppet-lib-file_concat'
    mysql:            'git://github.com/puppetlabs/puppetlabs-mysql'
    postgresql:       'git://github.com/puppetlabs/puppetlabs-postgresql'
    puppet:           'git://github.com/theforeman/puppet-puppet'
    stdlib:           'git://github.com/puppetlabs/puppetlabs-stdlib'
    tftp:             'git://github.com/theforeman/puppet-tftp'


  symlinks:
    foreman: "#{source_dir}"
